server.port: ${SERVER_PORT:1000}

spring:
  application.name: db-migration
  servlet.multipart:
    max-file-size: ${MAX_FILE_SIZE:5MB}
    max-request-size: ${MAX_REQUEST_SIZE:5MB}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/local_db}
    username: ${DB_USER:user}
    password: ${DB_PASS:password}
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
  sql.init.mode: always


logging:
  level:
    ROOT: INFO
  file.name: logs/${LOG_NAME:db-migration.log}
  logback.rollingpolicy.max-history: ${MAX_LOG_HISTORY:14}

credential.configuration:
  private-key: ${PRIVATE_KEY}
  public-key: ${PUBLIC_KEY}
  prefix: ${CREDENTIAL_PREFIX:thisisprefix}
  postfix: ${CREDENTIAL_POSTFIX:thisispostfix}

file.configuration:
  upload-path: ${UPLOAD_FILE_PATH:files/}