server.port: ${SERVER_PORT:1000}

spring:
  application.name: db-migration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/local_db}
    username: ${DB_USER:user}
    password: ${DB_PASS:password}
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update


logging:
  level:
    ROOT: INFO
  file.name: logs/${LOG_NAME:db-migration.log}
  logback.rollingpolicy.max-history: ${MAX_LOG_HISTORY:14}

