name: Maven Build

on: [push]

jobs:
  maven_build:
    runs-on: ubuntu-latest
    name: maven_build
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build project with Maven
        run: mvn verify